name: "Environment Setup"
description: "Composite action to set up our environments in a standard way"

runs:
  using: "composite"
  steps:
    - name: "Set Build and Test Targets" 
      run: |
        echo "TEST_TARGET=x86_64-unknown-linux-gnu" >> $GITHUB_ENV
        echo "BUILD_TARGET=wasm32-wasi" >> $GITHUB_ENV
      shell: bash
    - name: "Code Checkout"
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: "Rust Toolchain Setup"
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        targets: $TEST_TARGET,$BUILD_TARGET
        components: rustfmt, clippy
