name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: "Environment Setup"
        uses: ./.github/base
      - name: "Build Codebase"
        run: cargo build --all --all-targets --target=$BUILD_TARGET
