name: clippy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: "Environment Setup"
        uses: ./.github/base
      - name: "Lint Codebase"
        run: cargo clippy -- --deny warnings --target=$BUILD_TARGET
