name: deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: "Environment Setup"
        uses: ./.github/base
      - name: Deploy
        uses: fastly/compute-actions@v5
        with:
          verbose: true
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
        